name: A workflow for group 8 App
on: push

jobs:
  build:
    name: Group 8 action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup network
        run: |
    
          docker pull mysql
          docker run -d --name mysql-dbserver
      - name: Build with Maven
        run: mvn package
      - name: Build
        run: docker build -t group8 .
      - name: Run image
        run: docker run  --name semcontainer group8
      - name: view logs
        run: docker logs semcontainer
